open-dollar/od-app

src/components/Icons/Identicon.tsx, src/components/Navbar.tsx, src/components/WalletModal/index.tsx, src/containers/Safes/CreateSafe.tsx, src/containers/Safes/ModifySafe.tsx, src/hooks/useActiveWeb3React.ts, src/hooks/useContract.ts, src/react-app-env.d.ts, src/services/blockchain.ts, src/utils/helper.ts, yarn.lock
Closes #2 
- Adds logic to prompt Metamask to switch to Optimism Goerli
- Adds some TS type improvements  (ExternalProvider must be extended to have on & removeListener properties because ExternalProvider only provides a base case of functionality--see relevant issue [here](https://github.com/ethers-io/ethers.js/discussions/3230)
- Adds ts-ignore to useContract.ts functions because some types (Erc20 & Multicall) don't play well with the Contract interface from @ethersproject/contracts
- Adds a new .yarn-lock to prevent yarn install from continuing to fail
- Prettier fixes (pushed in separate commit--the first and third commit are my main changes)
Before change
https://github.com/UseKeyp/open-dollar-app/assets/47253537/d8c155bc-7011-4b9b-874c-0a47fb646c47
After change …
=> Issue #2: Switch network improvement 

package.json, src/App.tsx, src/containers/Safes/Stats.js, src/containers/Safes/index.tsx, src/hooks/useStats.js, src/utils/graph.js, src/utils/helpers.js, src/utils/queries.js, yarn.lock
closes #25
- Stats are now displayed on the "/" home page
- The old splash page is removed
=> Page routing and stats

src/containers/Safes/Stats.js, src/containers/Safes/index.tsx, src/containers/Shared.tsx, src/hooks/useStats.js, src/utils/graph.js, src/utils/helpers.js, src/utils/queries.js
Closes #35 
- Header was being rendered conditionally but since we removed the splash page we don't need this logic anymore
- I also ran prettier in a separate commit so might want to view by commits
Before 
After
=> Issue #35: Fix disappeared header

src/containers/Vaults/index.tsx
closes #44 
- Stats now under main content
https://github.com/UseKeyp/od-app/assets/47253537/6982f60d-f480-4413-bd21-e0b8d20ef575
=> Issue #44: Reorder components on index page

src/assets/eth-icon.svg, src/assets/nfts-icon.svg, src/containers/Analytics/DataCard.tsx, src/containers/Analytics/index.tsx
closes #60 
Are in `open-dollar-app/src/containers/Analytics/index.tsx`
```js
const analiticsData = [
// totalCollateralLocked, 
// outstandingOd,
// vaultNFTs 
]
const systemRatesData = [
// annualStabilityFee,
annualRedemptionRate,
eightHourlyRedemptionRate
]
const systemInfoData = [
// circulation,
// feesPendingAuction,
// totalFeesEarned,
globalDebtUtilizationData,
globalDebt
]
const Prices = [
marketPrice, // check for market price OD not HAI
redemptionPriceData,
// liquidityUniswap,
// marketPriceODG,
]
```
@pi0neerpat
=> Stats page

src/components/NavLinks.tsx, src/components/Navbar.tsx
closes #67 
- Changed screen sizes when menu items update
https://github.com/UseKeyp/od-app/assets/36742189/d7736635-9b8d-4058-896e-dda2807d61d0
=> Make header responsive

src/containers/Shared.tsx, src/containers/Vaults/index.tsx
=> Data fetching errors

src/components/VaultStats.tsx, src/containers/Vaults/VaultHeader.tsx, src/utils/helper.ts
closes #85 
- Removed buttons from header
- Modified formatWithCommas function to allow specify minimum number of decimals
=> QA - Vault Details

src/containers/Vaults/Review.tsx, src/hooks/useSafe.ts, src/services/TransactionUpdater.tsx, src/utils/gebManager/index.ts
Closes #82 
The reason this was happening was because there was no liquidation data being mapped to STN and TOTEM, the last two assets in our SDK tokens list. The problem was that fetchLiquidationData in our SDK was returning data for all of the assets that are not collateral (everything except OD and ODG). However, in the app we were calling the SDK fetchLiquidationData function and mapping the data to the assets list again to store the liquidation for each asset, but we weren't filtering out the assets that aren't collateral (OD and ODG). This means we've being assigning wrong liquidation data to all of the assets (including OD and ODG), so by the time we reached STN and TOTEM (items 6 and 7 of the token array) we didn't have any more liquidation data to map to tokens.
Basically, the …
=> Issue #82: QA - Vault creation

src/containers/Vaults/VaultDetails.tsx
Closes #119 
- Added a function called fetchSingleVaultData that will get the safe data from a safe's ID -> we get the OD proxy address for that user -> we call the owner read function on the proxy -> we get a list of the user's safes -> we find the right safe and format it correctly using formatUserSafe before saving it in state
Note that the long string is the ABI for an OD proxy contract (there is no read function on the contract, just an OWNER variable, so although the read function is auto-generated I wasn't sure how to shorten that into a smaller ABI string that works)
https://github.com/open-dollar/od-app/assets/47253537/3577de7d-5bc9-40d7-bcb6-6e696ecd4c18
=> Issue #119: Show vaults you don't own

src/containers/Shared.tsx, src/services/checkSanctions.ts, src/utils/i18n/en.json
closes #114 
- Add a new sanctionsCheck to the network connection logic -- a user once connected can't click buttons. Also a toast message appears with "This wallet is not allowed to connect" messaging
MetaMask testing
https://github.com/open-dollar/od-app/assets/47253537/c773ca4e-841b-4859-8457-e00163e44b0d
Wallet connect 
https://github.com/open-dollar/od-app/assets/47253537/fde6329c-6003-4b3d-9bc2-1a4974a4e310
Coinbase wallet
https://github.com/open-dollar/od-app/assets/47253537/896016e6-b3e5-4255-8746-84675624d048
=> Issue #114: Add sanctions screening

src/containers/Shared.tsx, src/services/checkSanctions.ts, src/utils/i18n/en.json
Closes #145
- CORS logic is working now 
Testing sanctions logic by triggering when identifications.length === 0 (I've since changed it bc we should only trigger this when identifications.length > 0)
=> Issue #145: New screening endpoint from Bot

src/containers/Auctions/index.tsx
- WSTETH should be default on auctions page rather than WETH
=> WSTETH as default on auctions page

src/components/Modals/LiquidateSafeModal.tsx, src/utils/i18n/en.json
Closes #137
- Renamed safe to vault
- Once transaction is confirmed, close modals, then refresh page to see the closed status
Example 1 (very fast confirmation)
https://github.com/open-dollar/od-app/assets/47253537/03f6abf8-6d8c-4dc3-85c5-1a2456718a4e
Example 2 (slow confirmation)
https://github.com/open-dollar/od-app/assets/47253537/04765198-ad16-4e4c-bedd-27a8de8b5fa6
=> Issue #137: QA: Liquidation copy / page forwarding

src/components/Button.tsx, src/components/Navbar.tsx
Closes #159 
- Consolidates components in navbar to prevent components from overlapping "app, auctions, stats" section
- Added an unstyled feature to button because we may want the features of a button without opinionated padding and margins
prototype here: prototype: https://www.figma.com/proto/uJdTlxdVIJNozrmGtqQQvq/OpenDollar-App?page-id=480%3A423&type=design&node-id=480-424&viewport=569%2C360%2C0.29&t=bAI7uWFqWEmEUt3C-8&scaling=min-zoom&starting-point-node-id=480%3A424&hide-ui=1
Desktop
Responsive
https://github.com/open-dollar/od-app/assets/47253537/7366d8a5-5d34-4c91-b35e-c226b6e82794
Demo
https://github.com/open-dollar/od-app/assets/47253537/1217ee68-12e7-4929-ab25-2054fee8f8cc
=> Issue #159: Add New Address/Token Header Component 

src/containers/Analytics/index.tsx
Closes #170 
- Total collateral locked no longer hardcoded--adds all the collateral locked and then the number is formatted with formatDataNumber
^ This number is accurate given the sum of collateral locked in the table:
=> Issue #170: Stats - Total collateral locked

src/containers/Analytics/index.tsx
Closes #173 
Renamed Analytics to Stats
=> Issue #173: Stats Header

.example.env, cypress/support/commands.ts, package.json, src/chains.ts, src/components/WalletModal/index.tsx, src/utils/chains.ts, src/utils/constants.ts, src/utils/contractsDescription.ts, src/utils/helper.ts, src/utils/interfaces.ts, yarn.lock
Closes #184 
Need to update SDK to be able to test this--currently we can't initialize a Geb object until we have the sepolia contracts ready
=> Issue #184: Prepare app for Sepolia

src/containers/Analytics/ContractsTable.tsx
Closes #166 
- Allows contract description to expand to full width of its container
Responsive
https://github.com/open-dollar/od-app/assets/47253537/1b163eec-f00b-41b6-a4ee-63fd93e15d23
Mobile
Desktop is same as before
Mobile comparison (app deployment is on the right side)
=> Isssue #166: Ch.22 QA & Cleanup

src/containers/Vaults/VaultDetails.tsx
Closes #189 
- Liquidation data is always null when wallet is not connected -- I had to fetch liquidation data here and populate the store so we have the necessary data to render the vault
Fetch vault when not connected
https://github.com/open-dollar/od-app/assets/47253537/9a86e385-37c2-4bc5-8a71-86fa31742436
Fetch vault when connected still works 
https://github.com/open-dollar/od-app/assets/47253537/e63766a4-9dbb-4d83-a92e-6b52ce261837
=> Issue #189: Fetch vault even when wallet not connected

package.json, src/components/VaultStats.tsx, yarn.lock
the app portion of this svg-playground PR: https://github.com/open-dollar/svg-playground/pull/10
- Renames renderSvg to generateSvg
=> Issue #8 (app PR): Package Cleanup

src/components/VaultStats.tsx
Closes #191 
- couldn't replicate seeing scrollbars so waiting on confirmation from tim that it fixed the scrollbar issue
=> Issue #191: Scrollbar sometimes appears on vaults

package.json, src/containers/Vaults/VaultDetails.tsx, yarn.lock
=> 1-16-deployment

src/components/Footer.tsx
- Correcting TOS and privacy policy links in the app to be correct
=> Fix TOS and privacy policy links

package.json, src/App.tsx, src/components/CookieBanner.tsx, src/components/Footer.tsx, src/containers/Shared.tsx, src/containers/Vaults/CreateVault.tsx, src/containers/Vaults/Stats.js, src/hooks/useTokenApproval.tsx
- Fix lint:fix script
- Fix format and format:fix scripts
- Lint and format scripts run
=> Chore: Run ESLint and Prettier

package.json, yarn.lock
=> Deployment 02-02-2024

src/App.tsx, src/components/NavLinks.tsx, src/components/Navbar.tsx, src/components/Steps.tsx, src/containers/Deposit/index.tsx, src/containers/Vaults/index.tsx, src/model/safeModel.ts, src/utils/i18n/en.json
- Deposit now default page
- nav now switches between Vaults, Deposit, Auctions, Stats 
- Create facilitator greyed out in vaults
- Error handling to prevent app from crashing on Arb mainnet (SDK changes for this are in https://github.com/open-dollar/od-sdk/pull/50) 
Note that in the navbar the OD price is blank because it's not on mainnet--should we remove for now or add a default value?
Do you want me to do #238 in this PR too so we can launch the deposit page at the same time?
https://github.com/open-dollar/od-app/assets/47253537/028e3bad-9aff-49f7-b935-e8cb78ee8b56
=> Issue #248: Prep app for TVL

src/App.tsx, src/containers/Deposit/DepositDetails.tsx, src/containers/Vaults/VaultDetails.tsx, src/containers/Vaults/VaultHeader.tsx
Able to pull some initial data from the pool using a local build of the sdk
=> Add deposit details page

src/App.tsx, src/components/Footer.tsx, src/components/NavLinks.tsx, src/components/Navbar.tsx, src/containers/Deposit/DepositDetails.tsx, src/containers/Deposit/index.tsx, src/containers/Vaults/Stats.js, src/model/safeModel.ts, src/utils/i18n/en.json
Closes #238
- Adds styles to the deposit page title
- Minor cleanup
=> Issue #238: Add Deposit Page

src/services/checkSanctions.ts
related to https://github.com/open-dollar/od-bot/pull/72
=> Add new bot URL 

public/tracking.js, src/components/VaultStats.tsx, src/containers/Vaults/ModifyVault.tsx, src/hooks/useGeb.ts
Closes #314 
- I pushed up some lint and prettier fixes with this, but they're in a separate commit so check out the first commit for the main changes
- Added a useEffect that will calculate the USD value of the collateral as the user adds or removes numbers from the input box
=> Issue #314: OD-4 wstETH price

src/components/Footer.tsx
closes #294 
- Creates new footer based on new designs with some minor changes (mobile responsive mode was not in design so I made this look the best as possible, I did not include launch app and the big social icons because these were based on the webflow design and redundant)
Desktop
Mobile
Responsive
https://github.com/open-dollar/od-app/assets/47253537/8a411196-9dfd-457e-bb51-901e9eaf45fc
=> Issue #294: App Redesign: new footer

src/components/CookieBanner.tsx, src/components/Footer.tsx
closes #316 
- Changed cookie banner design
Eslint error in Footer. Do I remove not used variables? 
```
const handleLinkClick = async (e: React.MouseEvent<HTMLElement>, disable = false, externalLink = '') => {
if (disable) {
e.preventDefault()
}
popupsActions.setShowSideMenu(false)
if (externalLink) {
window.open(externalLink, '_blank')
e.preventDefault()
}
}
```
=> Issue #316. App Redesign: Cookie Consent Banner

src/chains.ts, src/components/WalletModal/index.tsx, src/containers/Vaults/ModifyVault.tsx, src/hooks/useSafe.ts, src/utils/constants.ts
Closes #338 
The issue was improper undefined/null handling.
=> UX Cleanup - Withdraw/Deposit routing

src/components/Modals/BridgeModal.tsx, src/components/NavLinks.tsx, src/containers/Bridge/BridgeFundsForm.tsx, src/containers/Bridge/index.tsx, src/containers/Shared.tsx, src/model/bridgeModel.ts, src/model/index.ts, src/utils/formatBridgeUrl.ts, src/utils/interfaces.ts
closes: #350
Sets up store state and actions
=> set up state for bridge

package.json, yarn.lock
=> 4-9-24 deployment

src/components/Modals/ConnectedWalletModal.tsx, src/components/Modals/WaitingModal.tsx, src/components/NavLinks.tsx, src/components/Navbar.tsx, src/components/SideMenu.tsx
=> Redesign Header and Side Menu

src/components/Steps.tsx, src/containers/Shared.tsx, src/containers/Vaults/CreateVault.tsx
=> fix route & state

src/components/AccountCardsWeb3ReactV2.tsx, src/components/Button.tsx, src/components/Loader.tsx, src/components/connectorCards/MetaMaskCard.tsx, src/components/connectorCards/WalletConnectV2Card.tsx, src/containers/Vaults/CreateVault.tsx, src/containers/Vaults/ModifyVault.tsx, src/hooks/useActiveWeb3React.ts
=> Fix UI bugs, wallet not connecting on first load, type issues, and styles

package.json, yarn.lock
Closes https://github.com/open-dollar/od-app/security/dependabot/27
=> Remove gh-pages

src/components/Button.tsx, src/components/Loader.tsx, src/components/Modals/WaitingModal.tsx
=> QA 2 - loaders spinners & button

src/components/CookieBanner.tsx, src/components/Footer.tsx, src/components/NavLinks.tsx, src/components/WalletModal/index.tsx, src/containers/Analytics/ContractsTable.tsx, src/containers/Analytics/DataTable.tsx, src/containers/Analytics/index.tsx, src/containers/Vaults/CreateVault.tsx, src/containers/Vaults/VaultDetails.tsx, src/containers/Vaults/VaultList.tsx
Closes #383 
1. Removed close icon from modal (connecting wallet)
2. Adjusted price cards on stats page
3. Added info icon for tooltips and adjusted layout
4. Which one design to choose for links?
5. fixed create vault btn text color and the whole btn
6. Removed duplicate checkbox
7. Highlighted App page on '/' and 'vaults' routs
8. Removed Stats component from vault page
9. Added paddings to footer and added shadows to cookies box
10. Fixed back btn
=> Issue 383. QA - Web Redesign: (part 3)

src/components/Navbar.tsx
=> Disable liquidity button temporarily in navbar

src/components/Navbar.tsx, src/components/Steps.tsx, src/containers/Analytics/ContractsTable.tsx, src/containers/Vaults/index.tsx
Closes #407
- Fixed Stepper width (responsiveness was broken) (wasn't the part of the issue)
- Added 15px paddings to header
- Removed ProxyFactory row with address from Stats page
- Show Tokens btn in Navbar only for Arbitrum Sepolia network
- No test token btn in side menu for now, but I can address this issue in #406
=> Issue #407. QA: Header, test tokens

src/containers/Shared.tsx
=> Add more countries to geoblock

src/components/NavLinks.tsx, src/components/SideMenu.tsx
=> Issue #406. QA: Side menu

.gitignore, src/components/Button.tsx, src/components/ConnectWalletStep.tsx, src/containers/Analytics/index.tsx, src/containers/Vaults/CreateVault.tsx, src/hooks/TransactionHooks.tsx, src/hooks/useSafe.ts
=> Create account if no facilitator, Error handling, precision

src/components/Footer.tsx
Closes #450 
https://github.com/open-dollar/od-app/assets/36742189/62101092-057d-41ce-b6a1-46aecb5cd1a3
=> Issue #450. Footer column alignment

src/hooks/useSafe.ts
=> liquidation penalty price

src/containers/Earn/PoolBlock.tsx
=> Issue #491. APY tooltip

src/containers/Bolts/Affiliate.tsx, src/containers/Bolts/QuestBlock.tsx, src/containers/Bolts/index.tsx, src/containers/Bolts/quests.tsx, src/containers/Earn/index.tsx
=> Botls page leanup

src/components/Modals/LowGasModal.tsx, src/components/Steps.tsx, src/containers/Shared.tsx, src/model/popupsModel.ts, src/utils/tokens.ts
closes #507
- I've commented opening a bridge modal after checking gas. Please let me know if I need to put it back
=> Issue #507. Bridge: low gas improvements

src/components/AuctionsOperations/AuctionsTransactions.tsx, src/components/Navbar.tsx, src/components/SideMenu.tsx, src/components/Steps.tsx, src/components/VaultStats.tsx, src/components/WalletModal/index.tsx, src/containers/Analytics/index.tsx, src/containers/Earn/EarnDetails.tsx, src/containers/Earn/index.tsx, src/containers/Shared.tsx, src/containers/Vaults/CreateVault.tsx, src/containers/Vaults/ModifyVault.tsx, src/containers/Vaults/Stats.js, src/containers/Vaults/wrapEth/TxConfirmation.tsx, src/hooks/usePoolData.ts, src/model/auctionModel.ts, src/model/index.ts, src/model/nitroPoolsModel.ts, src/model/poolDataModel.ts, src/model/safeModel.ts, src/services/blockchain.ts, src/utils/auctions.ts, src/utils/wrapEther.ts
closes #409 
closes #501 
closes #471 
- Fixed svg re-rendering (#471) by memoizing the svg image so it won't re-render unless its stats re-render
- Input is reset bug (#501) seems to be fixed, it seemed to be caused by the svg re-rendering because I couldn't replicate it after the fix (see screenshots)
- Fixed a bug where wallet addresses were getting caught in step 2 (create vault facilitator) even after the vault facilitator was created. The solution was adding account, provider, and geb to a dependency array in Shared.tsx so that once geb is properly populated we trigger the proper step checks again and the user's proxy won't be undefined so we can move to the next step
- Fixed the excessive approval bug (for some reason when we were calling 
```ts
await window.ethereum.request({ …
```
=> Issue #409: Reduce redundant RPC calls

src/components/VaultStats.tsx
=> Issue #463. QA: Vault modification new "After" text

src/components/VaultStats.tsx, src/containers/Vaults/ModifyVault.tsx, src/containers/Vaults/VaultHeader.tsx
closes #525
- added check for not existing network
=> NFV corner radius #525

src/containers/Vaults/CreateVault.tsx, src/containers/Vaults/ModifyVault.tsx, src/model/safeModel.ts, src/react-app-env.d.ts
closes #591 
- Adds events for deposit, withdraw, and borrow to Matomo
I think I need access to the Matomo dashboard to actually test this
=> Add deposit, withdraw, and borrow to Matomo analytics

src/components/Modals/WaitingModal.tsx, src/components/Steps.tsx, src/containers/Shared.tsx, src/containers/Vaults/VaultList.tsx, src/containers/Vaults/index.tsx, src/model/safeModel.ts
=> New "initializing" loader

src/components/LinkButton.tsx, src/containers/Earn/EarnBlock.tsx, src/containers/Vaults/ModifyVault.tsx
=> Borrow + Deposit tabs cleanup

src/containers/Explore/ExploreTable.tsx, src/containers/Explore/index.tsx, src/utils/generateSVGRing.ts, src/utils/helper.ts
closes #630 
- Implemented new function to generate ring svg
- Reduced SVG size dramatically on desktop and mobile
- Fixes SVG rendering issue 
The cause of the SVG rendering issue is that the .chart tag for the first chart rendered was essentially hijacking the CSS for all the rest of the vaults on the page--in order to keep these in sync we pass in dynamic class names so each vault has unique CSS selectors
SVG rendering issue fixed
https://github.com/user-attachments/assets/30418459-1b2c-4acd-9f88-8fc0496f2502
Desktop
Mobile
=> Issue #630: Explore page design improvements

src/containers/Explore/ExploreTable.tsx
- Dev deployment failed because there was a file that was merged that still uses history.push which we have to update to use the new useNavigate hook
Routing logic working
https://github.com/user-attachments/assets/86be6d8c-0912-4953-a630-7efc1f23c46b
=> Fix useHistory issue in dev deployment

src/GlobalStyle.tsx, src/components/AccountCardsWeb3ReactV2.tsx, src/components/ApproveToken.tsx, src/components/AuctionBlock.tsx, src/components/BidLine.tsx, src/components/Bolts/AddressCell.tsx, src/components/Dropdown.tsx, src/components/LinkButton.tsx, src/components/Modals/WaitingModal.tsx, src/components/NavLinks.tsx, src/components/Navbar.tsx, src/components/NotificationPopup.tsx, src/components/Slider.tsx, src/components/WalletModal/Option.tsx, src/components/connectorCards/Card.tsx, src/containers/Analytics/DataTable.tsx, src/containers/Auctions/CollateralAuctions/CollateralAuctionBlock.tsx, src/containers/Bolts/Leaderboard.tsx, src/containers/Bolts/QuestBlock.tsx, src/containers/Deposit/DepositFunds.tsx, src/containers/Earn/PoolBlock.tsx, src/containers/Earn/index.tsx, src/containers/GeoBlockContainer.tsx, src/containers/Vaults/ModifyVault.tsx, src/utils/retry.ts
closes #536 
- Removed as many 'any' and ts-ignore as I could
=> Replace all 'any' with correct Types

public/index.html, src/containers/Explore/ExploreTable.tsx, src/containers/Vaults/VaultDetails.tsx, src/utils/interfaces.ts, src/utils/themes/dark.ts, src/utils/themes/light.ts
closes #556 
- changed 'loading' state logic
- show error if vault does not exists
- fixes Tracking error by adding %PUBLIC_URL% to a link in index.html file
=> QA: Tracking error, empty vault

package.json, src/GlobalStyle.tsx, src/components/MetaTags.tsx, src/containers/Analytics/index.tsx, src/containers/Auctions/index.tsx, src/containers/Bolts/index.tsx, src/containers/Bridge/index.tsx, src/containers/Earn/index.tsx, src/containers/Vaults/VaultList.tsx, src/containers/Vaults/index.tsx, src/utils/metaInfo.ts, yarn.lock
closes #647 
- added bg color to body tag
- created MetaTag component
- created metaInfo file with the info at the one place
=> App meta tags

src/GlobalStyle.tsx
=> Fixing background color

src/components/Steps.tsx, src/containers/Shared.tsx
=> Remove low gas modal
