open-dollar/od-app

src/containers/Safes/CreateSafe.tsx

Closes #7
- Created function leftInputPriceUSD which tracks the price in USD of a user's input for an asset
Price calculated w/wETH
https://github.com/UseKeyp/open-dollar-app/assets/47253537/f8f95dda-8fdf-4ffc-a9f2-179704b283f9
Price calculated w/OP 
https://github.com/UseKeyp/open-dollar-app/assets/47253537/8fa9df9e-97a7-49f7-88c9-8e67e7361caa

Issue #7: Display amount dollar value

---

src/components/WalletModal/index.tsx

Closes #2 
I was finally able to replicate, not sure why it wasn't replicating for me before
- Checks chain ID and if the chain ID is not 420 (op goerli) it will prompt to switch networks
Before
https://github.com/UseKeyp/od-app/assets/47253537/4b827437-9abf-4eab-9941-0381611cd6a9
After
https://github.com/UseKeyp/od-app/assets/47253537/c26c35e4-b175-47a3-bba9-0f9a87e6f615

Issue #2: Switch network improvement

---

src/containers/Vaults/CreateVault.tsx

closes #47
- When clicking wrap eth it'll open https://wrapeth.com/ in a new window
- Note that https://wrapeth.com/ only supports arbitrum & OP mainnet not the testnets. The other bridge that Joseph mentioned (https://app.optimism.io/bridge) doesn't actually support arbitrum - optimism bridging, it just links to other third-party bridges
https://github.com/UseKeyp/od-app/assets/47253537/9e0d4dd4-e7be-484e-a81f-d2448b4cf6e3

Issue #47: Wrap eth link updated 

---

src/containers/Shared.tsx

Closes #46 
- Conditional rendering was causing the "waiting for confirmation" pop up to not appear on account creation
After fix
https://github.com/UseKeyp/od-app/assets/47253537/bdc943f8-f5e0-4a6d-a7d8-3ae7c47bb7e6

Issue #46: Awaiting tx modal missing

---

src/components/VaultStats.tsx

Closes #48 
Only thing I'm not sure about is whether we want the "after: X" to always show up, even when the fields haven't been modified & if we want them to be "justify-content: space-between" or closer together
Desktop
https://github.com/UseKeyp/od-app/assets/47253537/95a43aaf-a183-4359-9720-f120a3c09194
Mobile
https://github.com/UseKeyp/od-app/assets/47253537/482621ab-9530-4ae6-9015-a49dd67903a4

Issue #48: QA Vault details 

---

src/components/ConnectedWalletInfo.tsx
src/components/Icons/CopyIcon.tsx
src/connectors/coinbaseWallet.ts

Closes #90 
- Fixed disconnecting from wallet connect from wallet info modal throws error
- Fixed duplicate copy address buttons
- Change Coinbase Wallet app name from "od-on-op" to "od-on-arb"
Before: copy button duplicated
After: copy button fixed
Before: disconnect error 
https://github.com/UseKeyp/od-app/assets/47253537/ba43e7dc-083f-4afa-b84b-00b67833c545
After: disconnect fixed
https://github.com/UseKeyp/od-app/assets/47253537/04da72b9-b00f-41fd-ab87-061fc3b90817

Issue #90: QA cleanup - disconnect from modal, double copy button

---

src/components/connectorCards/Card.tsx
src/components/connectorCards/Status.tsx

Closes #81 
- change wallet name to 20px
- status / description text is now normal size not bold
Before
After

Issue #81: QA - Wallet connect modal styling 

---

src/components/Web3ReactManager/index.tsx

Closes #80 
- We now connect to the permitted network if we're not connected to any of the wallet providers in order to populate the stats page
https://github.com/UseKeyp/od-app/assets/47253537/ba84e92b-14d7-4093-ae4b-3fb1dcabc484

Issue #80: QA - Add RPC to always show stats

---

src/hooks/useSafe.ts

Closes #99 
- Added validation to ensure user does not try to deposit & borrow when OD === 0
https://github.com/open-dollar/od-app/assets/47253537/e32e8581-fd74-437f-8798-66b9888370a2

Issue #99: Validate OD Borrowed > 0 During Deposit & Borrow

---

src/App.tsx
src/components/ToastPayload.tsx
src/components/WalletModal/index.tsx
src/components/connectorCards/CoinbaseWalletCard.tsx
src/components/connectorCards/MetaMaskCard.tsx
src/components/connectorCards/WalletConnectCard.tsx
src/components/connectorCards/WalletConnectV2Card.tsx
src/containers/Shared.tsx
src/model/connectWalletModel.ts
src/utils/constants.ts
src/utils/helper.ts

Closes #89
- Added logic to check if user is on right network when *already* connected to the app and if not, prompt them to switch networks--i'm specifying arbitrum goerli here but do we want to add support for arbitrum yet?
- Removed the overlay over the body when on the wrong network (setBlockBody(true))
- Removed connectEagerly logic from wallet components (the wallet persists anyway thanks to our context provider so it's unnecessary) 
- Added error handling to a token fetching call that was throwing errors that weren't caught
- Removed unused ENS logic from wallet components
Switch networks 
https://github.com/UseKeyp/od-app/assets/47253537/0702255d-93b6-4e39-b8a3-9aa9bfa0a37c
Connect eagerly not needed--wallet connection persists anyway …

Issue #89: QA - Network selection

---

src/containers/Vaults/index.tsx

Closes #107 
- Vault creation bug was caused by additional validation that was added to a fetchSafe() call in Vaults/index.tsx. 
We can validate that geb and tokensData are not null but address is always an empty string on re-render so the fetchSafes call never happens
Vault populates without refresh (from 12 -> 13 vaults)
https://github.com/open-dollar/od-app/assets/47253537/053800c2-d471-465a-a4a4-c84acd7ca8f7

Issue #107: Vault creation blank screen 

---

src/components/Footer.tsx
src/components/Navbar.tsx
src/containers/Shared.tsx

Closes #113 
Fixed by setting no-wrap and having width expand dynamically
Fixed footer issues by removing fixed positioning, moving image to footer, modifying padding
I determined this needs to be added at the smart contract level--in the SDK the only function available to fetch safes is via fetchUserSafes in the SDK and this is passing in an address. I looked in the ABI for functions we could use to fetch safes in other ways and in HaiSafeManager.json we have the following functions available:
```
"getSafes(address)": "61120929",
"getSafes(address,bytes32)": "7896835e",
"getSafesData(address)": "4e1db2bb",
```
We need a read method in the ABI to fetch safes by ID. In the SDK the ReadMe shows this:
```
let safe = await geb.getSafe(4)
```
However, this was never implemented anywhere
OD …

Issue #113: QA vaults hidden

---

src/components/Navbar.tsx
src/components/connectorCards/MetaMaskCard.tsx
src/connectors/index.ts
src/connectors/walletConnectV2.ts
src/containers/Analytics/index.tsx
src/containers/Shared.tsx

Closes #120 
Modal closes when connected
https://github.com/open-dollar/od-app/assets/47253537/ccdcfe5f-eacd-43c3-b6d3-6a632d346c6f
Test token button changes (note that the add token to wallet dropdown is now a little larger than the button itself to avoid the text wrapping to two lines--if you want I can just have it wrap)
https://github.com/open-dollar/od-app/assets/47253537/053d9c22-790e-4c21-a63f-9be9e17e5c96
Navbar has more responive layout when OD balance is large (note that OD is not formatted correctly in this example because I edited the text directly in the DOM to show it can be responsive with multiple #'s) 
https://github.com/open-dollar/od-app/assets/47253537/1415a649-4df8-402b-be0e-35e29000cd6d
OD balance is dollar currency formatted, commas & 2 decimals (example number is …

Issue #120: QA 9-18

---

src/containers/Shared.tsx

Closes #135 
- Now token data is fetched in the main body component (```<Shared>```) which is where all the vaults, auctions, & stats logic is occurring. The polling stops on unmount of ```<Shared>``` to prevent memory leaks
see console message incrementing
https://github.com/open-dollar/od-app/assets/47253537/b8d131d2-bfd0-4c1a-8c03-0c703b95f815
see console message incrementing
https://github.com/open-dollar/od-app/assets/47253537/5f3485af-2a5d-432b-9e38-aa800c50a221

Issue #135: QA: App data polling

---

src/components/NavLinks.tsx
src/components/Navbar.tsx
src/components/SideMenu.tsx

Closes #133 
OD balance when 3810 OD
OD balance when 10 OD
OD balance when 10418.29
Dropdowns close when clicking outside
https://github.com/open-dollar/od-app/assets/47253537/4ab2b905-b20e-4f9f-aa80-274930a23273
Mobile menu centered, claim tokens button added to mobile menu
https://github.com/open-dollar/od-app/assets/47253537/457ddb7d-be01-4167-9f93-8f59a4cfb524

Issue #133: QA: Mobile menu / dropdown

---

src/components/VaultBlock.tsx
src/components/VaultStats.tsx
src/utils/helper.ts
src/utils/index.test.ts

Closes #130 
- The thresholds in the app are now consistent with the SVG issues
```
Low Risk 151% - 200% and above
Elevated Risk 137% - 150%
High Risk 120% - 136%
Liquidation Risk 0% - 119%
```
- Changed "No" to "Closed" when a safe is liquidated
- Updated tests

Issue #130: Update collateral thresholds

---

src/hooks/useSafe.ts

Closes #136 
- Now creating a vault has the same validation check that deposit and borrow has--ensuring OD borrowed > 0
for the record we added this logic modifying a vault in this PR: https://github.com/open-dollar/od-app/pull/100/files 
before fix, without validation
after fix, with validation
can create a vault once OD borrowed

Issue #136: QA: New vault debt minimum

---

src/containers/Shared.tsx
src/containers/Vaults/Stats.js
src/containers/Vaults/index.tsx

Closes #144 
- Fetch safe data every 60 seconds like how we're fetching token data every 15 seconds
- Cleaned up some components
What stats data do we want to fetch every 60 seconds? I noticed that the <Stats> component and even the StatsProvider isn't currently being accessed. Do we want to call fetchDataAnalytics every 60 seconds?
https://github.com/open-dollar/od-app/assets/47253537/a1f0bedd-7cbb-4f9a-a423-d27c50d0b126

Issue #144: Poll Stats and Vault data

---

src/components/WalletModal/index.tsx

- Arbitrum goerli network should have AGOR as its currency (arbitrum one is correctly ETH in the app) and its name should be Arbitrum Goerli
No warning when adding network now

Fix arbitrum goerli config

---

src/hooks/useSafe.ts

Closes #158 
- [] Closing a vault is an exception to the rules above, therefore debt can be 0 OD
Why would debt be 0 OD when closing a vault? We can't close the vault unless enough collateral is deposited to meet the collateralization ratio. Otherwise we can just pay back the debt and the vault will be closed.
example:
Creating a vault
Creating a vault
Deposit and borrow
Repay and withdraw

Issue #158: Debt floor, collateral validation

---

src/containers/Vaults/CreateVault.tsx

Closes #163 
- Adjusts the z-index of tooltips on create vault screen to 99
https://github.com/open-dollar/od-app/assets/47253537/d7917e24-c289-45c5-92a4-1e478589303d

Issue #163: Fix create vault tooltips

---

src/containers/Shared.tsx
src/containers/Vaults/Stats.js
src/containers/Vaults/VaultDetails.tsx

Closes #165 
- Edited our old stats component to match the Figma designs (though I changed safes -> vaults and took out some sections that we don't have stats for)
- Added the component to the index route and the vaults page
Currently the collateral ratio section is empty--what numbers do we want to use for these? The hai team was using  stats?.globalCollateral, stats?.globalDebt, stats?.liquidationPrice, and stats?.liquidationCRatio to calculate it. We have globalDebt via fetchAnalyticsData but not sure about the others
Also, can't merge this until the SDK is updated to have fetchPoolData
Index page desktop
Vaults page desktop
Index page mobile
Vaults page mobile
Responsive
https://github.com/open-dollar/od-app/assets/47253537/dfca7956-e546-4c55-9caa-a78e21cf61dc

Issue #165: Global Stats 

---

package.json
yarn.lock

Forgot to bump the SDK version to the latest version as part of https://github.com/open-dollar/od-app/pull/171#event-10761031953

Bump SDK to 1.5.6-rc.2

---

src/containers/Analytics/index.tsx

Closes #172 
- Token symbol now beside amount locked for each collateral

Issue #172: Add token symbol to total locked

---

package.json
src/components/VaultStats.tsx
src/containers/Vaults/VaultHeader.tsx
src/utils/i18n/en.json
yarn.lock

Closes #168 
**Can't be merged until opendollar/svg-playground 1.0.0 is published**
- New vaults page that corresponds to app design
- Vaults page uses new renderSvg function coming from svg-playground package (separate PR)
Desktop
Mobile
Responsive
https://github.com/open-dollar/od-app/assets/47253537/aa3971cd-525a-498b-afc4-96e3d7c43ad0
Depositing collateral
Borrowing OD
Another vault example

Issue #168: Add SVG

---

src/containers/Auctions/index.tsx

Closes #182 
- Reordered auctions to be collateral, surplus, debt
- Collateral now is open by default
New order
Demo
https://github.com/open-dollar/od-app/assets/47253537/21d69be1-ff46-47f0-8831-1fc94c4fbba5

Issue #182: Re-order auctions

---

src/containers/Vaults/CreateVault.tsx
src/containers/Vaults/ModifyVault.tsx
src/containers/Vaults/Stats.js
src/utils/helper.ts
src/utils/index.test.ts

Closes #180 
- Limited balance amounts on vaults when creating/modifying them to two decimal places
- Changed liquidation logic from currentLiquidationRatioAsDecimal <= liqRatio to currentLiquidationRatioAsDecimal < liqRatio and if they're equal then return 3 (elevated)
- Replaced collateral ratio in global stats with total collateral locked (global collateral ratio was not being used before)
Before limiting decimal points on balance and OD owed amounts
After limiting decimal points on balance and OD owed amounts
Repay not throwing errors (note that svg rendering logic will have to be changed in the svg generator package so that it will show elevated rather than liquidation after repaying)
https://github.com/open-dollar/od-app/assets/47253537/549f758a-15cb-428b-889d-dbe5b7518019
Global …

Issue #180: FE QA 10-30

---

src/containers/Auctions/CollateralAuctions/CollateralAuctionBlock.tsx

Closes #139 
After fixing the SDK parseEvents issue the division by zero error happens after an auction has been settled. I fixed this by adding validation to ensure price calculation never involves division by 0. 
I also changed the auctionPrice calculation to be 0 when maxCollateral = 0. (Otherwise it ends up returning a huge number because marketPriceOD is multiplied by odBalance and it throws off the discount % as well)
Before fix
After fix
https://github.com/open-dollar/od-app/assets/47253537/877f6697-69b3-4da1-b8bd-975edc61a433
After fix 2
https://github.com/open-dollar/od-app/assets/47253537/199c67c7-2cab-48cf-a8d9-d33df1520bae

Issue #139: QA: Collateral Auction empty error

---

src/containers/Vaults/ModifyVault.tsx

Closes #196 
- The default # of decimals for the TokenInput component is 4 but this is not precise enough to satisfy our validation that ensures we don't leave residual OD when repaying OD so I changed to 5 for this particular use of TokenInput
Before
After example 1
https://github.com/open-dollar/od-app/assets/47253537/36cc255e-315c-4fb0-b71a-ed60b35ea1a7
After example 2
Repay successful
https://github.com/open-dollar/od-app/assets/47253537/40bbefce-8349-471e-a0bd-3727578b68fb

Issue #196: Repay & Withdraw Rounding Issue 

---

.example.env
README.md

relates to Issue #39: Subgraph documentation: https://github.com/open-dollar/od-sdk/pull/40
- Adds the subgraph fallback to the .env.example and adds documentation about the fallback subgraph to the readme

Relates to Issue #39: Subgraph documentation 

---

src/components/VaultStats.tsx

relates to https://github.com/open-dollar/od-app/issues/205
this is the od-app PR, but the svg-generator PR is here: https://github.com/open-dollar/svg-generator/pull/13
- We need to pass the infinity symbol to the svg-generator so that we're not passing NaN when the collateral ratio is infinity
Successfully working with new svg-generator code

Relates to Issue #205: Bug: collateral ratio NaN

---

src/containers/Vaults/ModifyVault.tsx

Closes #208 
- Now the USD price of the collateral is based off the user's *input* rather than the user's wallet balance. Note that this new behavior is for both deposit and borrow and repay and withdraw, do we want to limit it? (see demo below)
- I added the ts-ignore because singleSafe?.collateralName is type string and useTokenBalanceInUSD() expects a type TokenType, which will always be provided by singleSafe?.collateralName anyway
Demo
https://github.com/open-dollar/od-app/assets/47253537/0ff932c3-fe6e-4255-bbb3-11f1079c7f11

 Issue #208: Price showing total, not deposit amount

---

package.json
yarn.lock

Pat published new version of the svg-generator here https://github.com/open-dollar/svg-generator/issues/14#event-11379696097 and now we need to add it to the app
Screenshot (Note the infinite symbol rather than NaN):

Bump svg-generator version

---

src/components/TokenInput.tsx
src/containers/Vaults/Stats.js

Closes #247 
- Restricts leading zero input
- Allows initial character to be decimal point, but formats it as "0."
(Spamming zero in video but it isn't showing up)
https://github.com/open-dollar/od-app/assets/90171376/0d735cb6-a2a1-41e1-94f5-bc6b2c9862c7

Issue #247: Restrict Leading Zeros in TokenInput

---

package.json
tsconfig.json
yarn.lock

Closes #251 
- Addresses all the Dependabot alerts pertaining to the app (there will need to be other changes to the SDK and ABI packages to address those...like all the ones related to OpenZeppelin)
- Upgrades react, react-dom, axios, graphql, postcss, various testing library packages (jest & cypress)
- Removes unused & insecure babel dependencies
- Moves jest dependencies to dev dependencies
- noOverloadMatchesThisCall is set as false in the tsConfig because it's flagging 30+ styled components as having invalid props. The errors are just a type issue that we can address later but setting noOverloadMatchesThisCall to false allows us to keep using strict mode without crashing the app with all the type mismatches
- In prod we should set GENERATE_SOURCEMAP=false in the env because this gets …

Issue #251: Review dependabot alerts

---

src/utils/helper.ts

Closes #261 
- Because of the precision of values in the app totalCollateral can be less than zero if the user presses "max" (it's negative by something .000001). This validation ensures a vault action won't be considered safe in this case, and disables the user from trying to submit the transaction
Before, withdraw all collateral is incorrectly enabled
After, withdraw all collateral is correctly disabled

Issue #261: Disable withdrawing all collateral from vault

---

src/components/ConnectWithSelect.tsx
src/containers/Shared.tsx
src/utils/i18n/en.json

Closes #269 
- Gnosis safe does not support the arbitrum testnets (https://help.safe.global/en/articles/40795-supported-networks) so this PR includes logic for disabling the app if the user is using an arbitrum testnet while using the gnosis safe app viewer (detected with the IS_IN_IFRAME function) 
- I get rid of the disconnect button if the user is using the gnosis safe app viewer because the app viewer keeps trying to inject the gnosis safe network context into the app (like MM) and given that all of our connectors try to connect eagerly (ensuring that the provider instance will persist upon refresh and navigation) it will cause issues if users try to use other wallets while in the gnosis safe app context
App disabled & error message shown when user connects to testnet via gnosis safe …

Issue #269: Gnosis Safe Chain ID Issues 

---

package.json
src/components/Slider.tsx
src/connectors/NetworkConnector.ts
src/containers/Analytics/DataCard.tsx
src/containers/Vaults/VaultDetails.tsx
src/hooks/useGeb.ts
tsconfig.json
yarn.lock

closes #304 
Changes:
- update react types dependancy to match current react version used in app
- regenerate yarn.lock
- remove tsconfig.json setting causing error
- fixed misc. type errors
- updated easy-peasy dependency to ^5.1.0 to be compatible with react-18 types https://github.com/ctrlplusb/easy-peasy/issues/741

Issue #304: Fix Styled Components not Inheriting React Props

---

src/components/VaultStats.tsx
src/containers/Vaults/ModifyVault.tsx
src/hooks/useGeb.ts

Closes #308 
I changed it to show 3 decimals now. Considering the real amount can be 18 digits I think 3 is a good amount, especially since now when we press "max" when repaying it'll fill in the debt owed with more than just 3 decimals anyway if needed (see video below)
~~Before the app would max out at a user's wallet balance. I changed the "max" button logic to just fill in the max amount owed rather than the wallet balance amount~~
Reverted third change
Example of 3 decimal debt owed value and 2 decimal debt owed in USD 
Another example of 3 decimal debt owed value and 2 decimal debt owed in USD 
When debt is 0 then decimal rules don't apply
"Max" now fills in the whole amount owed when repaying
https://github.com/open-dollar/od-app/assets/47253537/ecb0785f-b4a3-4978-8da1-477e148ffc93

Issue #308: Debt owed, input owed amount

---

src/index.tsx

closes #327
#329 & #331 are separate issues
```TS
if ('ethereum' in window) {
;(window.ethereum as any).autoRefreshOnNetworkChange = false
}
```
Is deprecated, and no longer does anything + ```window.ethereum``` is will always result in a bug as you must check that both window, has loaded, then ethereum is loaded.
Since it doesn't do anything I just elected to remove it.

Remove deprecated check

---

src/chains.ts
src/components/Navbar.tsx
src/components/SideMenu.tsx
src/components/WalletModal/index.tsx
src/containers/Shared.tsx
src/containers/Vaults/Stats.js
src/containers/Vaults/index.tsx
src/hooks/useGeb.ts
src/utils/auctions.ts
src/utils/constants.ts
src/utils/wrapEther.ts

closes #335 
A few issues surfaced in this PR:
1. Typing for Geb was not correct, Network should be GebDeployment
2. There were no checks to see if the network switched to are supported prior to triggering functions
3. Too many functions are being triggered when geb changes
4. The Network error warning did not disappear after switching to correct chain
Additionally I noticed the overuse of the useEffect hook:
https://react.dev/learn/you-might-not-need-an-effect
Cleaning that up can come later, but 9 in 1 file is too much, and there too many hooks which are copy pasted in multiple files.

Prevent Network Errors on switch chain

---

src/containers/Vaults/VaultDetails.tsx
src/utils/i18n/en.json

Closes #330 
- Modifies managed_safe_warning to explain users who don't own the vault can only repay that vault
- New rendering logic for ModifySafe component that check isOwner and either enable only repay (if not owner) or enable everything (if owner)
User can only repay when not owner (can't click on deposit and borrow tab either)
https://github.com/open-dollar/od-app/assets/47253537/2f67cffd-24d6-442e-9196-5abe1ba6bd6c

Issue #330: Always show interactive element for vaults

---

src/chains.ts
src/components/WalletModal/index.tsx
src/containers/Analytics/DataTable.tsx
src/containers/Analytics/index.tsx
src/utils/constants.ts

Closes #321 
- Removed Annual Stability Fee
- Moved Redemption Rates to Price
- Removed column Borrow rate

Global stability fee is incorrect

---

src/components/VaultStats.tsx
src/containers/Vaults/VaultDetails.tsx
src/containers/Vaults/VaultHeader.tsx

Closes #298 
- Adds upper part of modify vault page
Differences from design:
- The border radius and size of the SVG are different in the design, but in order for us to change these we need to change them in the svg-generator which may or may not cause issues with the formatting of svg itself. I'd say we should avoid doing this because changing the size may warp the inside parts of the svg and the only difference it makes in the design is the border radius of the svg isn't 4px and the padding on the right-side part of the page (with all the vault stats in it) does not have as much padding as in the design
- We decided not to make the vault safety component (https://github.com/open-dollar/od-app/issues/296) so I just preserved the same list design that we had (but with updated fonts, …

Issue #298: App Redesign: Upper part of modify vault page

---

src/components/ConnectedWalletInfo.tsx
src/components/CookieBanner.tsx
src/components/LinkButton.tsx
src/components/Navbar.tsx
src/components/ToastPayload.tsx
src/components/VaultBlock.tsx
src/components/WalletModal/index.tsx
src/containers/Shared.tsx
src/containers/Vaults/ModifyVault.tsx
src/containers/Vaults/VaultDetails.tsx
src/containers/Vaults/index.tsx

Closes #384 
Now disables change button when connected with browser wallet
Now disables change button when connected with browser wallet
Create vault is appearing but can't test modify vault until we merge in Sero's ModifyVault.tsx changes
Fixed backgrounds of the toast and modal, we can't do the clickable thing because non-browser wallets don't support this
Added try catches to every network call in Shared.tsx w/debug statements and now we don't get these errors
Link updated
Sero fixed the ModifyVault.tsx problems in a separate PR
See screenshot
- Fixed border error (we cannot pass a boolean to the border property)
- Added back deleted code to ModifyVault.tsx (I was only able to test this flow once because of this create/modify vault errors mentioned above)
- Fixed node removal error we …

Issue #384: QA - Web Redesign (Part 4)

---

src/components/Brand.tsx
src/containers/Shared.tsx

Closes #403 
- Fixed lost wallet context when pressing navbar logo by making the logo an internal route rather than an tag
Wallet context lost when pressing logo
https://github.com/open-dollar/od-app/assets/47253537/a1af5f32-c27f-41c2-9430-696846e5d06d
No longer losing wallet context when pressing logo
https://github.com/open-dollar/od-app/assets/47253537/a2d183dd-f0c8-4723-84b9-2a8e768a7828

Issue #403: Lost wallet context when clicking navbar logo

---

src/containers/Analytics/index.tsx

Closes #446 
- Adds collateralJoin and collateralAuctionHouse to collaterals section of analytics page for each collateral

Issue #446: Display stats collateraljoin contracts

---

src/containers/Vaults/CreateVault.tsx

When we create a vault, our max button will reduce 5% of our max available as a buffer to ensure transactions succeeds, this was implemented on launch because we had transactions failing at max mint
closes: #455

Remove 5% Buffer On Vault Creation with Max Balance

---

src/hooks/useSafe.ts

Closes #462 
- Changed stability fee to have 2 decimals on the create vault page
Before
After

Issue #462: Vault creation decimals

---

Earthfile
src/containers/Vaults/CreateVault.tsx
src/containers/Vaults/ModifyVault.tsx
src/hooks/useCollateralBalances.ts
src/hooks/useSafe.ts
src/utils/helper.ts

closes #466 
I found out in useSafe.ts the app has been rounding the collateral amount the user has to two decimals and this has been a thing since we forked the app. This has been forcing us to do a lot of weird rounding. These fixes might clean that up a bit 
- When creating RETH vault the deposit amount may be valid but client-side validation is triggered
This issue was caused by two things
1) On vault creation we don't have access to availableCollateral (which represent's the user's balance for a selected collateral). It's always 0 for some reason. I don't know when this changed but I now use the logic that we use to display the user's balance (Balance: X) instead to do this. I created a new hook called useCollateralBalances which correctly calculates the user's balance of a …

Issue #466: RETH deposit bug

---

src/components/NavLinks.tsx
src/components/Navbar.tsx

closes #474 
- Made text for header elements 14 px
- Increased paddings for text btns
- Btns width is flexible now
- Added property for OdBalance to make it compact. But need someone to check if that is right. I am confused about 18 decimals.

Issue #474. Header QA

---

src/GlobalStyle.tsx
src/components/ToastBannerNetwork.tsx
src/containers/Earn/index.tsx
src/containers/Shared.tsx

Issue #451. HAI warning Banner 

---

src/containers/Vaults/CreateVault.tsx
src/containers/Vaults/ModifyVault.tsx
src/hooks/useCollateralBalances.ts
src/utils/tokens.ts

closes #564 
closes #561 
note I only increase the token decimals to 4--the USD values are staying at 2 since it seems unnecessary to show 4 for these
```
200 * liqRatio = minimumDeposit
200 * 1.3 = $230 
```
Still unresolved is the max button issue--the amount of debt that a user can take out according to the app is too high (see discussion in front end channel)
Max returns all 4 decimals of user's token balance
https://github.com/open-dollar/od-app/assets/47253537/f6ef1918-8971-4f67-876d-8eb932bb167b
Note the minimum deposit info in the CreateVault page
https://github.com/open-dollar/od-app/assets/472535
4 decimals modify vault page
4 decimals modify vault page (repay)
4 decimals create vault page

Issue #564: Vault creation- small deposit warning

---

src/hooks/useSafe.ts
src/utils/helper.ts

relates to #561 
- Adds a new function based off of returnAvailableDebt but with a 0.1% buffer to ensure the max OD taken out is not so high that the transaction fails.
Create vault (note the collateral ratio, if we wanted to use a smaller buffer we could probably do so)
https://github.com/open-dollar/od-app/assets/47253537/8b93fcc0-2e9a-4b2f-9d8d-7985b4bcdf94
Modify vault
https://github.com/open-dollar/od-app/assets/47253537/fcae27b7-fc15-4c90-a44c-5ca23e6f0481

Add buffer to max button in create/modify vault

---

src/components/VaultManager.tsx
src/containers/Vaults/VaultDetails.tsx
src/model/safeModel.ts

closes #508 
There were two problems causing the user not to be able to see vaults while seeing the app as another user
1) We were using history.push to navigate to the vaults list for a different user, but history.push is internal routing for react so it was conserving the current wallet's address in the state and causing issues when trying to fetch the current user's vaults and the different user's vaults at the same time
2) In state management we were sometimes setting setSingleSafe to a null value, which doesn't make any sense and was causing the vault to be set to null when viewed as another user (I'm not sure exactly why it was coming as null once it was fetched more than once but we can prevent this anyway)
I added the following fixes:
- When window.location is available we use …

Issue #508: Bug: View as another wallet 

---

package.json
src/components/AddressLink.tsx
src/components/Bolts/AddressCell.tsx
src/containers/Bolts/Leaderboard.tsx
src/containers/Bolts/index.tsx
src/hooks/useAddress.ts
src/model/boltsModel.ts
src/model/index.ts
yarn.lock

closes #580 
Fixed by creating boltsModel.ts and extracting the bolts info into our state management
Fixed by creating an AddressCell component, creating a skipEnsFlag on useAddress (for addresses not in top 10) and memoizing AddressCell
Fixed by moving declaration outside of hook
Added react-loading-skeleton
- Refactored useAddress to cache addresses in our state management for address it has already looked up
- Added skipEns flag to AddressLink.tsx because this is only being used to look up contract addresses so no need to waste RPC calls on looking up their ENS
Loading skeleton
https://github.com/open-dollar/od-app/assets/47253537/8ace5a96-7e48-4c03-b454-93a534a5ed92
Switching tabs = very few network calls, most info cached
https://github.com/open-dollar/od-app/assets/47253537/54d1b16a- …

Issue #580: QA release: Bolts

---

src/containers/Vaults/CreateVault.tsx

closes #589 
- Fixed the bug where right input not erased if there's already text in the field
we need to use the availableHai variable to represent the max of the right input. This is because after triggering onMaxRightInput the rightInput variable is always undefined, which was causing the right input to not be set to anything (it doesn't change). availableHai is the correct up-to-date amount given a left input
Some examples
https://github.com/open-dollar/od-app/assets/47253537/d01be642-f90f-4a20-afc8-d6c2ef8c4d08
Some more examples
https://github.com/open-dollar/od-app/assets/47253537/8c6a6f78-0ece-4d0a-b1fe-2685a027bae0

Issue #589: QA: create vault 

---

src/model/safeModel.ts

- I found PR #573 is breaking the vault list--when a user has multiple vaults and they click into one then when they go back and click into another the vault details won't refresh. I reverted that one line change in that PR
- This reintroduces the problem of when a user is viewing a vault as another user and they connect their wallet then the vault will disappear, which I'll have to find a new solution for
Multiple vaults can be viewed and refreshed appropriately
https://github.com/open-dollar/od-app/assets/47253537/11285f2b-7ab0-48b6-839b-c8c2cc6ddb90

Fix vault details not rendering when user has multiple vaults

---

src/containers/Vaults/CreateVault.tsx
src/containers/Vaults/ModifyVault.tsx
src/model/safeModel.ts

closes #593 
I had to make a couple changes from the original plan to have it conform with Matomo's requirements
- Matomo requires that we do addEcommerceItem before doing trackEcommerceOrder so I created 4 different addEcommerceItem products: "OD_Repaid", "OD_Borrowed", "COLLATERAL_Deposited", and "COLLATERAL_Withdrawn" where "COLLATERAL" is a variable representing the collateral name
- I added trackEcommerceOrder events for deposit, borrow, withdraw, repay 
The order ID has to be unique so we can't do the plan of doing total number of vaults + 1 or the existing vault ID because this would lead to nonsensical data if someone does more than one thing per vault
- I removed the deposit info I was adding to trackEvent because it's useless info to track the input value rather than the USD …

Issue #593:   Matomo e-commerce integration

---

src/hooks/useSafeData.ts
src/model/globalSafeModel.ts
src/model/index.ts
src/services/safes.ts
src/utils/gebManager/index.ts
src/utils/helper.ts
src/utils/interfaces.ts

closes #607 
- This properly populates a new globalStateModel object in our state management library with all the vault information for the 84 existing vaults
- I have it fetching the global vault state every 60 seconds just like the user vaults but maybe we want to change this
- I have it fetching the vault owners from the API because I assume it's more efficient than doing contract calls but this also means we should probably tweak the bot to allow us to call it with localhost without having to disable CORS
- I almost was able to fix the bug in #595 with this new object but I still need to tweak it some more

Issue #607: Add global vault state 

---

public/index.html

closes #612 
- I removed the async defer from the matomo JS scripts in index.html. In the deployment for this branch I don't see the error (after disabling ad block), but I also don't see the error in the dev deployment, only main

Issue #612: matomo race conditions

---

src/components/Navbar.tsx
src/components/SideMenu.tsx
src/components/VaultStats.tsx
src/containers/Earn/index.tsx

closes #616 
- added to wallet component in a navbar and sidemenu
- added to vault stats
- already exists in leaderboard 
- Do we use primary color for all skeletons or somewhere we use grey?
- Do we want to use skeletons for balance as well?
https://github.com/user-attachments/assets/16b5e8b7-bb28-4b14-b7ae-0029b5b84705
https://github.com/user-attachments/assets/5fd9fa16-ba3c-4a66-b88b-10dc1b8bb330
https://github.com/user-attachments/assets/5ebf0893-7aab-4e41-b142-429be0826909

Address ENS loading skeleton

---

src/containers/Earn/EarnBlock.tsx
src/containers/Explore/ExploreTable.tsx
src/containers/Vaults/VaultDetails.tsx

closes #619 
I added history.push to do internal routing instead. It looks like a lot of code has changed but that's because I had to refactor the code to be able to call history.push properly (since useHistory is a hook we couldn't call it in our regular method that we had before)
The infinite loop was being caused by a bunch of dependencies in our VaultDetails.tsx component that we didn't need--we only need to re-render a vault's details when either we're viewing a new vault (vault id changes) or the user connects/disconnects their wallet (geb changes). The rest are not necessary
Fixed in https://github.com/open-dollar/od-app/pull/639
These screenshots don't have the new explore page design, it's just this routing change
View vault from /explore when wallet not connected …

Issue #619: /explore continued

---

src/components/CreateVaultStep.tsx
src/components/StepsContent.tsx
src/components/connectorCards/WalletConnectV2Card.tsx
src/containers/Explore/ExploreTable.tsx
src/containers/Vaults/index.tsx
src/hooks/useActiveWeb3React.ts

closes #642 
- Fixes issue where wallet is not automatically re-connected on refresh
There was a line "if !(window.ethereum)" which was basically blocking the browser wallet from being able to reconnect automatically
- Fixes issue where a loading skeleton sometimes doesn't disappear in the onboarding section
I added a fallback that will load the image after 3 seconds if loading isn't set to true
- Partially fixed issue where wallet connect won't give up its connecton
By removing connector from the dependency array in WalletConnectV2Card we prevent an infinite loop from occurring that would prevent wallet connect from giving up its connection. Now we switch providers even if we're connected with wallet connect. The only issue remains that wallet connect doesn't realize when the websocket …

Issue #642: Reconnect on refresh

---

src/components/ConnectedWalletInfo.tsx
src/components/Navbar.tsx
src/components/SideMenu.tsx
src/components/Web3ReactManager/index.tsx

closes #663 
I had to make various changes to ensure that Gnosis Safe is integrated properly in the app, such as preventing the MetaMask or NetworkConnector from hijacking the app before GnosisConnector gets a chance to connect
- Disabled "change" in the change wallet modal for Gnosis Safe (in addition to MM) to prevent mixing connectors while inside of the gnosis app context
- setIsConnectorsWalletOpen(true) in the handleWalletConnect() function in the nav and sidebar was throwing errors when using the GnosisConnector (and we shouldn't be able to switch wallets while in the gnosis app context anyway) so I exclude GnosisConnector from this
- I disabled the app from automatically connecting to the network RPC while in the safe context because we can connect to an RPC via the gnosis safe …

Issue #663: Fix Gnosis Safe in app

---

src/containers/Analytics/index.tsx

Stability fee was being multiplied by redemption rate. I removed this to show the correct fees

fix stability fee by removing multiplication
